import { DashboardLayout } from '../types';

type Layouts = {
    [key: string]: { [key: string]: DashboardLayout[] };
};

export const defaultLayouts: Layouts = {
    standard: {
        lg: [
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 4, h: 3 },
            { i: 'kpi-newContacts', x: 4, y: 0, w: 4, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 8, y: 0, w: 4, h: 3 },
            { i: 'featured-contact', x: 0, y: 3, w: 3, h: 8 },
            { i: 'review-prompt', x: 3, y: 3, w: 3, h: 8 },
            { i: 'ai-insights', x: 6, y: 3, w: 6, h: 8 },
            { i: 'chart-contactsByStatus', x: 0, y: 11, w: 6, h: 10 },
            { i: 'chart-appointmentsByMonth', x: 6, y: 11, w: 6, h: 10 },
        ],
        md: [ // 10 cols
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 5, h: 3 },
            { i: 'kpi-newContacts', x: 5, y: 0, w: 5, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 3, w: 5, h: 3 },
            { i: 'ai-insights', x: 5, y: 3, w: 5, h: 8 },
            { i: 'featured-contact', x: 0, y: 6, w: 5, h: 8 },
            { i: 'review-prompt', x: 0, y: 14, w: 5, h: 8 },
            { i: 'chart-contactsByStatus', x: 5, y: 11, w: 5, h: 11 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 22, w: 10, h: 10 },
        ],
        sm: [ // 6 cols
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 3, h: 3 },
            { i: 'kpi-newContacts', x: 3, y: 0, w: 3, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 3, w: 6, h: 3 },
            { i: 'chart-contactsByStatus', x: 0, y: 6, w: 6, h: 9 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 15, w: 6, h: 9 },
            { i: 'ai-insights', x: 0, y: 24, w: 6, h: 8 },
            { i: 'featured-contact', x: 0, y: 32, w: 6, h: 8 },
            { i: 'review-prompt', x: 0, y: 40, w: 6, h: 8 },
        ],
        xs: [ // 4 cols
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 4, h: 3 },
            { i: 'kpi-newContacts', x: 0, y: 3, w: 4, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 6, w: 4, h: 3 },
            { i: 'chart-contactsByStatus', x: 0, y: 9, w: 4, h: 9 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 18, w: 4, h: 9 },
            { i: 'ai-insights', x: 0, y: 27, w: 4, h: 8 },
            { i: 'featured-contact', x: 0, y: 35, w: 4, h: 8 },
            { i: 'review-prompt', x: 0, y: 43, w: 4, h: 8 },
        ],
        xxs: [ // 2 cols
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 2, h: 3 },
            { i: 'kpi-newContacts', x: 0, y: 3, w: 2, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 6, w: 2, h: 3 },
            { i: 'chart-contactsByStatus', x: 0, y: 9, w: 2, h: 9 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 18, w: 2, h: 9 },
            { i: 'ai-insights', x: 0, y: 27, w: 2, h: 8 },
            { i: 'featured-contact', x: 0, y: 35, w: 2, h: 8 },
            { i: 'review-prompt', x: 0, y: 43, w: 2, h: 8 },
        ],
    },
    analytics: {
        lg: [
            { i: 'chart-contactsByStatus', x: 0, y: 0, w: 8, h: 8 },
            { i: 'kpi-totalContacts', x: 8, y: 0, w: 4, h: 3 },
            { i: 'kpi-newContacts', x: 8, y: 3, w: 4, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 8, y: 6, w: 4, h: 2 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 8, w: 12, h: 8 },
            { i: 'ai-insights', x: 0, y: 16, w: 12, h: 8 },
        ],
        md: [
            { i: 'chart-contactsByStatus', x: 0, y: 0, w: 10, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 8, w: 10, h: 8 },
            { i: 'kpi-totalContacts', x: 0, y: 16, w: 5, h: 3 },
            { i: 'kpi-newContacts', x: 5, y: 16, w: 5, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 19, w: 5, h: 3 },
            { i: 'ai-insights', x: 5, y: 19, w: 5, h: 8 },
        ],
        sm: [
            { i: 'chart-contactsByStatus', x: 0, y: 0, w: 6, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 8, w: 6, h: 8 },
            { i: 'kpi-totalContacts', x: 0, y: 16, w: 3, h: 3 },
            { i: 'kpi-newContacts', x: 3, y: 16, w: 3, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 19, w: 6, h: 3 },
            { i: 'ai-insights', x: 0, y: 22, w: 6, h: 8 },
        ],
        xs: [
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 4, h: 3 },
            { i: 'kpi-newContacts', x: 0, y: 3, w: 4, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 6, w: 4, h: 3 },
            { i: 'chart-contactsByStatus', x: 0, y: 9, w: 4, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 17, w: 4, h: 8 },
            { i: 'ai-insights', x: 0, y: 25, w: 4, h: 8 },
        ],
        xxs: [
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 2, h: 3 },
            { i: 'kpi-newContacts', x: 0, y: 3, w: 2, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 6, w: 2, h: 3 },
            { i: 'chart-contactsByStatus', x: 0, y: 9, w: 2, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 17, w: 2, h: 8 },
            { i: 'ai-insights', x: 0, y: 25, w: 2, h: 8 },
        ],
    },
    compact: {
        lg: [
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 4, h: 3 },
            { i: 'kpi-newContacts', x: 4, y: 0, w: 4, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 8, y: 0, w: 4, h: 3 },
            { i: 'featured-contact', x: 0, y: 3, w: 4, h: 8 },
            { i: 'review-prompt', x: 4, y: 3, w: 4, h: 8 },
            { i: 'ai-insights', x: 8, y: 3, w: 4, h: 8 },
            { i: 'chart-contactsByStatus', x: 0, y: 11, w: 12, h: 9 },
        ],
        md: [
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 5, h: 3 },
            { i: 'kpi-newContacts', x: 5, y: 0, w: 5, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 3, w: 10, h: 3 },
            { i: 'featured-contact', x: 0, y: 6, w: 5, h: 8 },
            { i: 'review-prompt', x: 5, y: 6, w: 5, h: 8 },
            { i: 'ai-insights', x: 0, y: 14, w: 10, h: 8 },
            { i: 'chart-contactsByStatus', x: 0, y: 22, w: 10, h: 9 },
        ],
        sm: [
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 3, h: 3 },
            { i: 'kpi-newContacts', x: 3, y: 0, w: 3, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 3, w: 6, h: 3 },
            { i: 'featured-contact', x: 0, y: 6, w: 6, h: 8 },
            { i: 'review-prompt', x: 0, y: 14, w: 6, h: 8 },
            { i: 'ai-insights', x: 0, y: 22, w: 6, h: 8 },
            { i: 'chart-contactsByStatus', x: 0, y: 30, w: 6, h: 9 },
        ],
        xs: [
             { i: 'kpi-totalContacts', x: 0, y: 0, w: 4, h: 3 },
            { i: 'kpi-newContacts', x: 0, y: 3, w: 4, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 6, w: 4, h: 3 },
            { i: 'featured-contact', x: 0, y: 9, w: 4, h: 8 },
            { i: 'review-prompt', x: 0, y: 17, w: 4, h: 8 },
            { i: 'ai-insights', x: 0, y: 25, w: 4, h: 8 },
            { i: 'chart-contactsByStatus', x: 0, y: 33, w: 4, h: 9 },
        ],
        xxs: [
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 2, h: 3 },
            { i: 'kpi-newContacts', x: 0, y: 3, w: 2, h: 3 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 6, w: 2, h: 3 },
            { i: 'featured-contact', x: 0, y: 9, w: 2, h: 8 },
            { i: 'review-prompt', x: 0, y: 17, w: 2, h: 8 },
            { i: 'ai-insights', x: 0, y: 25, w: 2, h: 8 },
            { i: 'chart-contactsByStatus', x: 0, y: 33, w: 2, h: 9 },
        ],
    }
};
