import { DashboardLayout } from '../types';

type Layouts = {
    [key: string]: { [key: string]: DashboardLayout[] };
};

export const defaultLayouts: Layouts = {
    standard: {
        lg: [
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 3, h: 2 },
            { i: 'kpi-newContacts', x: 3, y: 0, w: 3, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 6, y: 0, w: 3, h: 2 },
            { i: 'ai-insights', x: 9, y: 0, w: 3, h: 8 },
            { i: 'chart-contactsByStatus', x: 0, y: 2, w: 6, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 6, y: 8, w: 6, h: 8 },
            { i: 'featured-contact', x: 0, y: 10, w: 3, h: 8 },
            { i: 'review-prompt', x: 3, y: 10, w: 3, h: 6 },
        ],
        md: [ // 10 cols
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 5, h: 2 },
            { i: 'kpi-newContacts', x: 5, y: 0, w: 5, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 2, w: 5, h: 2 },
            { i: 'ai-insights', x: 5, y: 2, w: 5, h: 8 },
            { i: 'chart-contactsByStatus', x: 0, y: 4, w: 5, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 12, w: 10, h: 8 },
            { i: 'featured-contact', x: 5, y: 10, w: 5, h: 8 },
            { i: 'review-prompt', x: 0, y: 20, w: 5, h: 6 },
        ],
        sm: [ // 6 cols
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 6, h: 2 },
            { i: 'kpi-newContacts', x: 0, y: 2, w: 6, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 4, w: 6, h: 2 },
            { i: 'chart-contactsByStatus', x: 0, y: 6, w: 6, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 14, w: 6, h: 8 },
            { i: 'ai-insights', x: 0, y: 22, w: 6, h: 8 },
            { i: 'featured-contact', x: 0, y: 30, w: 6, h: 8 },
            { i: 'review-prompt', x: 0, y: 38, w: 6, h: 6 },
        ],
        xs: [ // 4 cols
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 4, h: 2 },
            { i: 'kpi-newContacts', x: 0, y: 2, w: 4, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 4, w: 4, h: 2 },
            { i: 'chart-contactsByStatus', x: 0, y: 6, w: 4, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 14, w: 4, h: 8 },
            { i: 'ai-insights', x: 0, y: 22, w: 4, h: 8 },
            { i: 'featured-contact', x: 0, y: 30, w: 4, h: 8 },
            { i: 'review-prompt', x: 0, y: 38, w: 4, h: 6 },
        ],
        xxs: [ // 2 cols
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 2, h: 2 },
            { i: 'kpi-newContacts', x: 0, y: 2, w: 2, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 4, w: 2, h: 2 },
            { i: 'chart-contactsByStatus', x: 0, y: 6, w: 2, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 14, w: 2, h: 8 },
            { i: 'ai-insights', x: 0, y: 22, w: 2, h: 8 },
            { i: 'featured-contact', x: 0, y: 30, w: 2, h: 8 },
            { i: 'review-prompt', x: 0, y: 38, w: 2, h: 6 },
        ],
    },
    analytics: {
        lg: [
            { i: 'chart-contactsByStatus', x: 0, y: 0, w: 8, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 8, w: 8, h: 8 },
            { i: 'kpi-totalContacts', x: 8, y: 0, w: 4, h: 2 },
            { i: 'kpi-newContacts', x: 8, y: 2, w: 4, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 8, y: 4, w: 4, h: 2 },
            { i: 'ai-insights', x: 8, y: 6, w: 4, h: 10 },
        ],
        md: [
            { i: 'chart-contactsByStatus', x: 0, y: 0, w: 10, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 8, w: 10, h: 8 },
            { i: 'kpi-totalContacts', x: 0, y: 16, w: 5, h: 2 },
            { i: 'kpi-newContacts', x: 5, y: 16, w: 5, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 18, w: 5, h: 2 },
            { i: 'ai-insights', x: 5, y: 18, w: 5, h: 8 },
        ],
        sm: [
            { i: 'chart-contactsByStatus', x: 0, y: 0, w: 6, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 8, w: 6, h: 8 },
            { i: 'kpi-totalContacts', x: 0, y: 16, w: 6, h: 2 },
            { i: 'kpi-newContacts', x: 0, y: 18, w: 6, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 20, w: 6, h: 2 },
            { i: 'ai-insights', x: 0, y: 22, w: 6, h: 8 },
        ],
        xs: [
            { i: 'chart-contactsByStatus', x: 0, y: 0, w: 4, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 8, w: 4, h: 8 },
            { i: 'kpi-totalContacts', x: 0, y: 16, w: 4, h: 2 },
            { i: 'kpi-newContacts', x: 0, y: 18, w: 4, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 20, w: 4, h: 2 },
            { i: 'ai-insights', x: 0, y: 22, w: 4, h: 8 },
        ],
        xxs: [
            { i: 'chart-contactsByStatus', x: 0, y: 0, w: 2, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 8, w: 2, h: 8 },
            { i: 'kpi-totalContacts', x: 0, y: 16, w: 2, h: 2 },
            { i: 'kpi-newContacts', x: 0, y: 18, w: 2, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 20, w: 2, h: 2 },
            { i: 'ai-insights', x: 0, y: 22, w: 2, h: 8 },
        ],
    },
    compact: {
        lg: [
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 3, h: 2 },
            { i: 'kpi-newContacts', x: 3, y: 0, w: 3, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 6, y: 0, w: 3, h: 2 },
            { i: 'ai-insights', x: 9, y: 0, w: 3, h: 8 },
            { i: 'chart-contactsByStatus', x: 0, y: 2, w: 6, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 6, y: 8, w: 6, h: 8 },
            { i: 'featured-contact', x: 0, y: 10, w: 6, h: 6 },
        ],
        md: [
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 5, h: 2 },
            { i: 'kpi-newContacts', x: 5, y: 0, w: 5, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 2, w: 5, h: 2 },
            { i: 'ai-insights', x: 5, y: 2, w: 5, h: 8 },
            { i: 'chart-contactsByStatus', x: 0, y: 4, w: 5, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 12, w: 10, h: 8 },
            { i: 'featured-contact', x: 5, y: 10, w: 5, h: 8 },
        ],
        sm: [
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 6, h: 2 },
            { i: 'kpi-newContacts', x: 0, y: 2, w: 6, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 4, w: 6, h: 2 },
            { i: 'chart-contactsByStatus', x: 0, y: 6, w: 6, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 14, w: 6, h: 8 },
            { i: 'ai-insights', x: 0, y: 22, w: 6, h: 8 },
            { i: 'featured-contact', x: 0, y: 30, w: 6, h: 8 },
        ],
        xs: [
             { i: 'kpi-totalContacts', x: 0, y: 0, w: 4, h: 2 },
            { i: 'kpi-newContacts', x: 0, y: 2, w: 4, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 4, w: 4, h: 2 },
            { i: 'chart-contactsByStatus', x: 0, y: 6, w: 4, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 14, w: 4, h: 8 },
            { i: 'ai-insights', x: 0, y: 22, w: 4, h: 8 },
            { i: 'featured-contact', x: 0, y: 30, w: 4, h: 8 },
        ],
        xxs: [
            { i: 'kpi-totalContacts', x: 0, y: 0, w: 2, h: 2 },
            { i: 'kpi-newContacts', x: 0, y: 2, w: 2, h: 2 },
            { i: 'kpi-upcomingAppointments', x: 0, y: 4, w: 2, h: 2 },
            { i: 'chart-contactsByStatus', x: 0, y: 6, w: 2, h: 8 },
            { i: 'chart-appointmentsByMonth', x: 0, y: 14, w: 2, h: 8 },
            { i: 'ai-insights', x: 0, y: 22, w: 2, h: 8 },
            { i: 'featured-contact', x: 0, y: 30, w: 2, h: 8 },
        ],
    }
};
